xts5: Fix missing string.h include.
It is needed for strcmp():
|   CC     checkfont.lo
| checkfont.c:492:16: warning: implicit declaration of function 'strcmp' is invalid in C99 [-Wimplicit-function-declaration]
|                                 if (str && strcmp(teststr, str) != 0) {
|                                            ^

Signed-off-by: Cyril Brulebois <kibi@debian.org>
Reviewed-by: Aaron Plattner <aplattner@nvidia.com>
Tested-by: Aaron Plattner <aplattner@nvidia.com>
Signed-off-by: Aaron Plattner <aplattner@nvidia.com>