tet: Fix "sccsid defined but not used" warnings.
For example:
    addarg.c:18: error: ‘sccsid’ defined but not used

These strings are seriously outdated, unused, and cause warnings.

Signed-off-by: Aaron Plattner <aplattner@nvidia.com>
Acked-by: Peter Hutterer <peter.hutterer@who-t.net>