tet: tet_getvar needs to take a const char* argument
config.c: In function ‘initconfig’:
config.c:394: error: passing argument 1 of ‘_initconfig’ from incompatible pointer type
config.c:328: note: expected ‘char * (*)(const char *)’ but argument is of type ‘char * (*)(char *)’

Signed-off-by: Aaron Plattner <aplattner@nvidia.com>
Reviewed-by: Jeremy Huddleston <jeremyhu@apple.com>
Reviewed-by: Peter Hutterer <peter.hutterer@who-t.net>