xts5: Fix missing unistd.h includes.
It's needed for sleep():
|   CC     gettime.lo
| gettime.c:159:23: warning: implicit declaration of function 'sleep' is invalid in C99 [-Wimplicit-function-declaration]
|         for (i=0; i<10; i++, sleep(2)) {
|                              ^

It is needed for alarm():
|   CC     settimeout.lo
| settimeout.c:155:2: warning: implicit declaration of function 'alarm' is invalid in C99 [-Wimplicit-function-declaration]
|         alarm((unsigned long)to);
|         ^

It is needed for unlink():
|   CC     checkarea.lo
| checkarea.c:296:2: warning: implicit declaration of function 'unlink' is invalid in C99 [-Wimplicit-function-declaration]
|         unlink(name);
|         ^
|   CC     verimage.lo
| verimage.c:307:3: warning: implicit declaration of function 'unlink' is invalid in C99 [-Wimplicit-function-declaration]
|                 unlink(errfile);
|                 ^
|   CC     savimage.lo
| savimage.c:187:6: waning: implicit declaration of function 'unlink' is invalid in C99 [-Wimplicit-function-declaration]
|                                         unlink(name);
|                                         ^

Signed-off-by: Cyril Brulebois <kibi@debian.org>
[aplattner@nvidia.com: squashed several similar commits]
Reviewed-by: Aaron Plattner <aplattner@nvidia.com>
Tested-by: Aaron Plattner <aplattner@nvidia.com>
Signed-off-by: Aaron Plattner <aplattner@nvidia.com>